"$schema" = 'https://starship.rs/config-schema.json'

# =============
# Custom Config
# =============

add_newline = false

[cmd_duration]
min_time = 500
show_milliseconds = true

[username]
show_always = true

[gcloud]
format = 'on [$symbol($project)]($style) '

[directory]
truncation_symbol = "‚Ä¶/"

[kubernetes]
disabled = false

# ====================
# No Nerd Fonts Preset
# ====================

[battery]
full_symbol = "‚Ä¢ "
charging_symbol = "‚á° "
discharging_symbol = "‚á£ "
unknown_symbol = "‚ùì "
empty_symbol = "‚ùó "

[erlang]
symbol = "‚ìî "

[fortran]
symbol = "F "

[nodejs]
symbol = "[‚¨¢](bold green) "

[pulumi]
symbol = "üßä "

[typst]
symbol = "t "
